Repository vega/editor, pull requests merged in 2019-03, with the labels that each got.

#251 Mode selection done after verifying
  src/components/app.tsx
Labels: bug

#249 Scroll Position of example portal restored.
  src/actions/editor.ts
  src/components/header/index.tsx
  src/components/header/renderer.tsx
  src/constants/default-state.ts
  src/reducers/index.ts
Labels: UX Development, enhancement

#314 Add signal listeners in componentDidUpdate
  src/components/signal-viewer/signalRow.tsx
Labels: enhancement
